
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database';

const SUPABASE_URL = "https://jpvjdpgtpjbrkcamyqie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwdmpkcGd0cGpicmtjYW15cWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDA1NTcsImV4cCI6MjA3MDExNjU1N30.dqVMnxYZ-BnsFDVmny2mISInwsVvXqd9FjyyJVYE74g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
